version: '3.8'
services:
  mitsuki-socketify:
    build:
      context: ./mitsuki-socketify
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  mitsuki-granian:
    build:
      context: ./mitsuki-granian
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  mitsuki-uvicorn:
    build:
      context: ./mitsuki-uvicorn
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  starlette-uvicorn:
    build:
      context: ./starlette-uvicorn
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  starlette-granian:
    build:
      context: ./starlette-granian
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  flask:
    build:
      context: ./flask
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  django:
    build:
      context: ./django
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  elysia:
    build:
      context: ./elysia
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  spring:
    build:
      context: ./spring_boot
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  express:
    build:
      context: ./express
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  gin:
    build:
      context: ./gin
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
